services:
  db:
    image: postgres:15
    container_name: voeux-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: voeuxdb
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./backend/sql/db.sql:/docker-entrypoint-initdb.d/db.sql
    ports:
      - "5432:5432"

  backend:
    build: 
      context: .
      dockerfile: backend/Dockerfile
    container_name: voeux-backend
    restart: always
    depends_on:
      - db
    environment:
      PGUSER: postgres
      PGPASSWORD: root
      PGDATABASE: voeuxdb
      PGHOST: db
      PGPORT: 5432

    # volumes:
    #   - ./backend/uploads:/app/uploads
    ports:
      - "3000:3000"

  # frontend:
  #   build: ./frontend
  #   container_name: voeux-frontend
  #   restart: always
  #   ports:
  #     - "8080:80"
  #   depends_on:
  #     - backend

volumes:
  db_data:
